name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment for the GitHub Actions runner
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0"

      # Install dependencies (optional, in case you have tests or other build steps)
      - name: Install dependencies
        run: npm install

      # Set up SSH agent to connect to EC2
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Deploy to EC2 instance via SSH
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/shop-backend  # Ensure the correct project directory

            # Pull the latest code from GitHub
            git pull origin main

            # Install dependencies
            npm install

            # Build Docker image
            docker build -t shop-backend .

            # Stop and remove any existing containers
            docker stop shop-backend || true
            docker rm shop-backend || true

            # Run the new Docker container, passing environment variables from GitHub Secrets
            docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
              -e RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }} \
              -e RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }} \
              --name shop-backend shop-backend

            exit
          EOF
